### PR TITLE
ubports-qa: add option to run a full upgrade on install

### PR DESCRIPTION
**Pull request by mardy**
The `apt upgrade` command never removes installed packages, meaning that
if a package from the PPA conflicts with installed packages, it won't be
installed or upgraded.

The `apt full-upgrade` command, on the other hand, allows installing or
upgrading all the packages from the PPA, even if that requires removing
some of the installed packages.

This commit makes the `apt full-upgrade` option available, but for the
sake of being cautious not to break the tester's system, let's keep the
`upgrade` option as the default one. Developers working on PRs which
are expected to cause package removals can instruct their testers to add
the `-f` option.

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Why not just always do a full-upgrade?

**Comment by UniversalSuperBox** [comment]
Yes, it seems better if it's always a full-upgrade.

**Comment by mardy** [comment]
> Yes, it seems better if it's always a full-upgrade.

OK. PR updated. :-)

**Review by UniversalSuperBox — APPROVED** [review]

**Comment by UniversalSuperBox** [comment]
QA info: If `sudo ubports-qa install` works roughly as you expect it to, this PR was successful. The ways it is fixed would be rather nuanced, so a regression test is better than a new functionality test here.

**Comment by cibersheep** [comment]
I have installed the contenthub update to test see: https://github.com/ubports/ubports-qa-scripts/pull/29#issuecomment-966618198
I had no other ppa installed. Process finished successfully

**Pull request merged**
